export const ADD_RESTAURANTS = 'ADD_RESTAURANTS';
export const FETCH_RESTAURANTS = 'FETCH_RESTAURANTS';
export const FILTER_RESTAURANTS = 'FILTER_RESTAURANTS';
export const SORT_RESTAURANTS = 'SORT_RESTAURANTS';